# Generated by Django 5.1.1 on 2024-09-20 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id_episode', models.AutoField(primary_key=True, serialize=False)),
                ('season_number', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Номер выпуска')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id_child', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=100, verbose_name='Имя ребенка')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='locations_of_pregnant_at_16_app.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id_father', models.AutoField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя отца')),
                ('father_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст отца')),
                ('father_photo', models.ImageField(blank=True, null=True, upload_to='fathers/', verbose_name='Фото отца')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='locations_of_pregnant_at_16_app.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Heroine',
            fields=[
                ('id_heroine', models.AutoField(primary_key=True, serialize=False)),
                ('heroine_name', models.CharField(max_length=100, verbose_name='Имя героини')),
                ('heroine_age', models.PositiveIntegerField(verbose_name='Возраст героини')),
                ('heroine_photo', models.ImageField(upload_to='heroines/', verbose_name='Фото героини')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heroine', to='locations_of_pregnant_at_16_app.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id_marker', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='locations_of_pregnant_at_16_app.episode', verbose_name='Эпизод')),
            ],
        ),
    ]
