# Generated by Django 5.1.1 on 2024-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_of_pregnant_at_16_app', '0002_alter_child_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Метка удалена'),
        ),
    ]
